name: Super-Linter

on: push

jobs: 
  super-lint:
    names: Lint code base
    runs-on: ubuntu-latest
    steps:
      - names: Checkout code
        uses: actions/checkout@v2
        
      - names Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
